# PostgreSQL (Supabase) Datasource Configuration
spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.okpavbhztaeqsjqbcnrs
spring.datasource.password=Grup@25Jobmatch

# JPA / Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# JWT Secret (em produção, use variáveis de ambiente)
app.jwt.secret=default_super_secret_key_that_is_long_and_secure_enough_for_hs256
app.jwt.expiration-ms=86400000
